name: Build and push to dist
run-name: copy-via-ssh
on:
  push:
    branches:
      - main
jobs:
  copy-via-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: create file with key
        run: echo "${{ secrets.SSH_KEY }}" > id_rsa
      - name: mkdir .ssh
        run: mkdir .ssh
      - name: add known hosts
        run: echo "${{ secrets.KNOWN_HOSTS }}" > .ssh/known_hosts
      - name: connect to server
        run: ssh -i id_rsa root@${{ secrets.HOST_ADDR }} "mkdir testest2"
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - name: Copy via ssh
      #   uses: garygrossgarten/github-action-scp@v0.8.0
      #   with:
      #     local: flsk
      #     remote: /home/admin/test
      #     host: ${{ secrets.HOST_ADDR }}
      #     username: ${{ secrets.HOST_USR }}
      #     password: ${{ secrets.SECRET_PASS }}
